name: ci-go-workflow
on:
    pull_request:
        branches:
            - develop
jobs:
    run-tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                go_version: [1.15, 1.14]
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v2
              with:
                 go-version: {{ matrix.go_version }}
            - run: go test math.go math_test.go
            - run: go run math.go
