name: ci-go-workflow
on:
    pull_request:
        branches:
            - develop
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-go@v2
              with:
                 go-version: 1.15
            - run: go test math.go math_test.go
            - run: go run math.go
            -
              name: Set up QEMU
              uses: docker/setup-qemu-action@v3
            -
              name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3
            -
              name: Build and push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: false
                tags: MrZethaz/go-test:latest
