name: ci-go-workflow
on: [push]
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-go@v2
              with:
                 go-version: 1.15
            - run: go test math.go math_test.go
            - run: go run math.go
